CREATE OR REPLACE PACKAGE PKGV_VAL_DB_MODEL IS

/*
Autor: Mauricio Garcia
Fecha: 27/11/2019
Version: 1.0

*/

PROCEDURE FNDB_REGISTRA_HUELLA;

PROCEDURE PRDB_INSERTAR_AUD_COLUMNA (prg_audcolumna AUD_COLUMNA%ROWTYPE);

PROCEDURE PRDB_INSERTAR_AUD_TABLA(prg_audtabla AUD_TABLA%ROWTYPE);

PROCEDURE PRDB_VALIDAHUELLA;

PROCEDURE PRDB_INSERTAR_LOG(prg_log LOG_CAMBIO_DB%ROWTYPE);

END PKGV_VAL_DB_MODEL;
